---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kaptoco/public_html/kapto/
    - export APPPATH=/home/kaptoco/public_html/kapto/StoreApp/
    - /bin/mkdir $APPPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R app $APPPATH
    - /bin/cp -R bootstrap $APPPATH
    - /bin/cp -R config $APPPATH
    - /bin/cp -R database $APPPATH
    - /bin/cp -R node_modules $APPPATH
    - /bin/cp -R resources $APPPATH
    - /bin/cp -R routes $APPPATH
    - /bin/cp -R storage $APPPATH
    - /bin/cp -R tests $APPPATH
    - /bin/cp -R vendor $APPPATH
    - /bin/cp .editorconfig $APPPATH
    - /bin/cp .env.example $APPPATH
    - /bin/cp .phpunit.result.cache $APPPATH
    - /bin/cp .styleci.yml $APPPATH
    - /bin/cp artisan $APPPATH
    - /bin/cp composer.json $APPPATH
    - /bin/cp composer.lock $APPPATH
    - /bin/cp package-lock.json $APPPATH
    - /bin/cp package.json $APPPATH
    - /bin/cp phpunit.xml $APPPATH
    - /bin/cp Procfile $APPPATH
    - /bin/cp server.php $APPPATH
    - /bin/cp webpack.mix.js $APPPATH